apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hello-minikube
  name: hello-minikube
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: hello-minikube
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hello-minikube
  name: hello-minikube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-minikube
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-minikube
    spec:
      containers:
        - image: diti123/springdemo:1.0.7
          name: springdemo
          resources: {}
status: {}